Repository The-Alice-In-Wonderland-Project/alicegame-2023, pull requests merged in 2023-10, with the labels that each got.

#5 docs: add team file
  Teams.md
Labels: hacktoberfest-accepted, admin-org

#6 Update README.md with founder was sick message
  README.md
Labels: hacktoberfest-accepted, admin-org

#17 feat: hyperlink contact info into Teams.md
  Teams.md
Labels: hacktoberfest-accepted, admin-org, Team Lead/Leadership

#13 feat: adding information about contributors and team leads
  Teams.md
Labels: hacktoberfest-accepted, admin-org

#27 25.10.2023 #22 Add Chapter 1 Paragraph 3 of Alice in Wonderland
  Alices-Adventures-in-Wonderland-by-Lewis-Carroll.md
Labels: hacktoberfest-accepted

#30 2023-10-25 23 Down a Rabbit Hole
  Alices-Adventures-in-Wonderland-by-Lewis-Carroll.md
Labels: hacktoberfest-accepted

#29 25.10.2023 feat(add-ch): Add chapter 1 paragraph 1 of Alice in Wonderland (#20)
  Alices-Adventures-in-Wonderland-by-Lewis-Carroll.md
Labels: hacktoberfest-accepted
